StandardDjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('public_area.urls', namespace='public_area')),
    path('private_area/', include('private_area.urls', namespace='private_area')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('locations/', include('locations.urls', namespace='locations')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import ToolListApiView,ToolDetailApiView, ToolTypesDetailApiView, ToolTypesListApiView, UserRecordView

app_name = 'api'

urlpatterns = [
    path('', ToolListApiView.as_view(), name='tool_list'),
    path('detail/<tool_code>', ToolDetailApiView.as_view(), name='tool_detail'),
    path('type', ToolTypesListApiView.as_view(), name='type_list'),
    path('type_detail/<type_id>', ToolTypesDetailApiView.as_view(), name='type_detail'),
    path('user/', UserRecordView.as_view(), name='user' )

]

locations/urls.py
from django.urls import path
from .import views

app_name = 'locations'

urlpatterns = [
    path('create/', views.LocationsCreateView.as_view(), name='create'),
    path('listView/', views.LocationListView.as_view(), name='listView'),
    path('update/<pk>/', views.LocationUpdate.as_view(), name='updateView'),
    path('delete/<pk>/', views.LocationDelete.as_view(), name='deleteView'),
]

locations/models.py
from django.db import models


class Locations(models.Model):
    
    name = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    code = models.CharField(max_length=100, null=True, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.address

locations/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Locations
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin


class LocationsCreateView(LoginRequiredMixin, CreateView):
    model = Locations
    fields = '__all__'
    success_url = reverse_lazy('locations:listView')


class LocationUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Locations
    fields = "__all__"
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('locations:listView')


class LocationListView(LoginRequiredMixin, ListView):
    model = Locations
    paginate_by = 15
    template_name = "locations/listView.html"


class LocationDelete(LoginRequiredMixin, DeleteView):
    model = Locations
    success_url = reverse_lazy('locations:listView')

locations/templates/locations/listView.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Locations View
{% endblock title %}

{% block content %}

<div class="container-flu">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-header card-header-success">
                <h4 class="card-title">Locations</h4>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover" id="StandardTable">
                    <thead class="text-danger">
                    <td>Name</td>
                    <td>Address</td>
                    <td>Code</td>
                    <td>Actions</td>
                    </thead>
                    <tbody>
                        {% for items in object_list %}
                            <tr>
                            <td>{{ items.name }}</td>
                            <td>{{ items.address }}</td>
                            <td>{{ items.code }}</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a href="{% url 'locations:updateView' items.pk %}" class="btn btn-warning btn-sm ">Update</a>
                                    <a href="{% url 'locations:deleteView' items.pk %}" class="btn btn-danger btn-sm ">delete</a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a class="btn btn-success" href="{% url 'locations:create' %}">Create New Location</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

locations/templates/locations/locations_confirm_delete.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Delete
{% endblock title %}

{% block content %}
<div class='container'>
    <h1>New Location</h1>
    <form method="post">
        {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    </form>
    </div>
{% endblock content %}

locations/templates/locations/locations_form.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create A Location.
{% endblock title %}

{% block content %}
<div class='container'>
    <h3>New Location</h3>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type='submit' class='btn btn-primary' value='Summit'>
        <a  href="{% url 'locations:listView' %}" class='btn btn-secondary'>Back</a>
    </form>
</div>
{% endblock content %}

locations/templates/locations/locations_update_form.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Location Update
{% endblock title %}

{% block content %}
<div class='container'>
    <h3>Update Locations</h3>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type='submit' class='btn btn-primary' value='Update'>
    </form>
    </div>
{% endblock content %}