StandardDjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('public_area.urls', namespace='public_area')),
    path('private_area/', include('private_area.urls', namespace='private_area')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('locations/', include('locations.urls', namespace='locations')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views, employees_view

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/signup.html'), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.Profile.as_view(), name='profile'),

    #  employees management
    path('listView/', employees_view.AccountsListView.as_view(), name='listView'),
    path('update/<pk>/', employees_view.AccountsUpdate.as_view(), name='updateView'),
    path('password_update/<pk>/', employees_view.update_password, name='password_update'),
    path('delete/<pk>/', employees_view.AccountsDelete.as_view(), name='deleteView'),

]

api/urls.py
from django.urls import path
from .views import ToolListApiView,ToolDetailApiView, ToolTypesDetailApiView, ToolTypesListApiView, UserRecordView

app_name = 'api'

urlpatterns = [
    path('', ToolListApiView.as_view(), name='tool_list'),
    path('detail/<tool_code>', ToolDetailApiView.as_view(), name='tool_detail'),
    path('type', ToolTypesListApiView.as_view(), name='type_list'),
    path('type_detail/<type_id>', ToolTypesDetailApiView.as_view(), name='type_detail'),
    path('user/', UserRecordView.as_view(), name='user' )

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from locations.models import Locations


class User(AbstractUser):
    image = models.ImageField(default='default.jpg', upload_to='profile_pics', null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_supervisor = models.BooleanField(default=False)
    location = models.ForeignKey(Locations, on_delete=models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        else:
            return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username','first_name', 'last_name', 'email', 'password1', 'password2','is_admin')
        model = User

accounts/views.py
from django.urls import reverse_lazy
from .forms import UserCreateForm
from django.views.generic import CreateView, TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User


class SignUp(SuccessMessageMixin, CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('accounts:signup')
    template_name = 'accounts/signup.html'
    success_message = 'You Successfully Sign Up'


class Profile(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

accounts/templates/accounts/employees/change_password.html
{% extends 'user_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Change Password
{% endblock title %}

{% block content %}
<div class='container'>
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Reset Password</h4>
                </div>
                    <div class="col-md-12" style="padding-top:20px">
                        <form method="POST">
                            {% csrf_token %}
                            <input hidden=true name=pk, value={{pk}}>
                              <div class="form-group">
                                <label for="Password1"> New Password</label>
                                <input type="password" class="form-control" id="Password1" name="password1" >
                              </div>
                              <div class="form-group">
                                <label for="Password2">Repeat New Password</label>
                                <input type="password" class="form-control" id="Password2"  name="password2">
                              </div>

                              <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>

{% endblock %}

accounts/templates/accounts/employees/listView.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Locations View
{% endblock title %}

{% block content %}

<div class='container'>



    <div class="card card-stats">

        <div class="card-header card-header-info card-header-icon">
          <h3 class="card-title">Users</h3>
        </div>

        <div class="card-body table-responsive">
            <table class="table table-hover" id="StandardTable">
                <thead class="text-danger">
                    <td>#</td>
                    <td>Name</td>
                    <td>Actions</td>
                </thead>
                <tbody>
                    {% for items in object_list %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><h4>{{ items }}</h4></td>
                        <td>
                            {% if user.is_admin %}
                                <div class="btn-group" role="group">
                                    <a href="{% url 'accounts:password_update' items.pk %}" class="btn btn-primary btn-sm ">Update Password</a>
                                    <a href="{% url 'accounts:updateView' items.pk %}" class="btn btn-warning btn-sm ">Update</a>
                                    <a href="{% url 'accounts:deleteView' items.pk %}" class="btn btn-danger btn-sm ">delete</a>
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                        <li>No Accounts yet.</li>
                    {% endfor %}
                </tbody>
            </table>
                <div class="btn-group" role="group">
                    <a class="btn btn-success" href="{% url 'locations:listView' %}">Locations</a>
                    <a class="btn btn-info" href="{% url 'accounts:signup' %}">Create a new User</a>
                 </div>
        </div>

    </div>

</div>

{% endblock content %}

accounts/templates/accounts/employees/profile.html
{% extends 'user_area/base.html' %}


{% block title %}
    Profile
{% endblock title %}
    

{% block content %}
    <div class="card" style="width: 28rem; text-align: center;  margin-left: auto; margin-right: auto;">
      <img src="{{user.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{user.username}}</h5>
        <p class="card-text">{{user.email}}</p>
        <p href="#" style="background-color:Blue;color:white">{{ user.location }}</p>
      </div>
    </div>
{% endblock content %}

accounts/templates/accounts/employees/user_confirm_delete.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Delete
{% endblock title %}

{% block content %}
<div class='container'>
    <h1>Delete Account</h1>
    <form method="post">
        {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    </form>
    </div>
{% endblock content %}

accounts/templates/accounts/employees/user_update_form.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update User
{% endblock title %}

{% block content %}
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Update {{form.username.value }}</h4>
                </div>
                    <div class="col-md-12" style="padding-top:20px">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type='submit' class='btn btn-primary' value='Update'>
                        </form>
                  </div>
            </div>
          </div>
        </div>
      </div>
      </div>

{% endblock content %}