StandardDjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('public_area.urls', namespace='public_area')),
    path('private_area/', include('private_area.urls', namespace='private_area')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('locations/', include('locations.urls', namespace='locations')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import ToolListApiView,ToolDetailApiView, ToolTypesDetailApiView, ToolTypesListApiView, UserRecordView

app_name = 'api'

urlpatterns = [
    path('', ToolListApiView.as_view(), name='tool_list'),
    path('detail/<tool_code>', ToolDetailApiView.as_view(), name='tool_detail'),
    path('type', ToolTypesListApiView.as_view(), name='type_list'),
    path('type_detail/<type_id>', ToolTypesDetailApiView.as_view(), name='type_detail'),
    path('user/', UserRecordView.as_view(), name='user' )

]

tools/urls.py
from django.urls import path
from .views import Home, CreateTool, CreateType, ListViewType, DeleteType, UpdateType, ReceiveTool


app_name = 'tools'


urlpatterns = [
    #  basic Tools
    path('',Home.as_view(), name='home'),
    path('create_tool',CreateTool.as_view(), name='create_tool'),
    path('create_tool/<code>', CreateTool.as_view(), name='create_tool'),
    path('receive_tool/', ReceiveTool.as_view(), name='receive_tool'),
    path('receive_tool/<code>', ReceiveTool.as_view(), name='receive_tool'),

    # for types
    path('create_type/', CreateType.as_view(), name='create_type'),
    path('list_type/', ListViewType.as_view(), name='list_type'),
    path('update/<pk>/', UpdateType.as_view(), name='update_type'),
    path('delete/<pk>/', DeleteType.as_view(), name='delete_type'),
]

tools/models.py
from django.db import models
from accounts.models import User
from locations.models import Locations


class Type(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tool(models.Model):
    code = models.CharField(max_length=225, unique=True)
    type = models.ForeignKey(Type, on_delete=models.DO_NOTHING, null=True, blank=True )
    tags = models.TextField(blank=True, null=True)
    quantity = models.IntegerField(default=1)
    active = models.BooleanField(default=True)
    current_user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    current_location = models.ForeignKey(Locations, on_delete=models.DO_NOTHING, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.type.name} | current user: {self.current_user} in {self.current_location} '


class TempImage(models.Model):
    image = models.ImageField(upload_to='temp_image/', blank=True, null=True)

tools/forms.py
from django import forms
from .models import Tool, Type, TempImage


class CreateTypeForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = '__all__'

class CreateToolCodeForm(forms.ModelForm):
    class Meta:
        model = Tool
        fields = ['type', 'tags', 'quantity', 'active']

class CreateToolNoCodeForm(forms.ModelForm):
    class Meta:
        model = Tool
        fields = ['code', 'type', 'tags', 'quantity', 'active']

class TempImageForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'class': 'form-control form-control-lg'})

    image = forms.ImageField()

tools/views.py
import datetime

from django.shortcuts import render
from django.views.generic import View,UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Tool, Type
from .forms import CreateTypeForm, CreateToolCodeForm, CreateToolNoCodeForm
from django.contrib.messages import success, error, views
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.shortcuts import redirect


#  Tools Views
class Home(LoginRequiredMixin, View):

    def get(self, request):
        context = {
            'list_objects': Tool.objects.all(),
        }
        return render(request, 'tools/home.html', context)


class CreateTool(LoginRequiredMixin, View):

    def get(self, request, code=None):

        if code:
            context = {
                'form': CreateToolCodeForm(),
                'code':code
            }
            return render(request, 'tools/create_or_update_tool/create_tool.html', context)
        return render(request, 'tools/create_or_update_tool/create_tool.html', {'form': CreateToolNoCodeForm()})

    def post(self,request, code=None):
        form_data = request.POST
        tool = Tool.objects.create(
            code = code if code else form_data['code'] ,
            type = Type.objects.get(id=form_data['type']),
            tags = form_data['tags'],
            quantity = form_data['quantity'],
            active = True if form_data['active'] == 'on' else False,
            current_user = request.user,
            current_location = request.user.location,
        )
        tool.save()
        success(request, 'successfully Tool Created.')
        return redirect('private_area:private_area')


class ReceiveTool(LoginRequiredMixin, View):

    def get(self, request, code=None):
        tool = Tool.objects.get(code=code)
        tool.current_user = request.user
        tool.current_location = request.user.location
        tool.save()
        success(request, f"You Successfully receive {tool.type} id={tool.code}")
        return redirect("private_area:private_area")

    def post(self,request):
        form_data = request.POST
        ## working in this area
        print(form_data)
        return render(request, 'tools/create_or_update_tool/create_tool.html', {'types': Type.objects.all()})



#  Types Views
class CreateType(LoginRequiredMixin, View):

    def get(self, request):
        context = {
            'form': CreateTypeForm(),
        }
        return render(request, 'tools/type_templates/type_form.html',context)

    def post(self,request):
        form = CreateTypeForm(request.POST)
        if form.is_valid():
            form.save()
            success(request, 'New Type Was created')
            return redirect('tools:create_type')
        error(request, 'There was a error ')
        return redirect('tools:create_type')


class ListViewType(LoginRequiredMixin, View):

    def get(self, request):
        context = {
            'list_objects': Type.objects.all(),
        }
        return render(request,'tools/type_templates/listView.html', context )


class DeleteType(LoginRequiredMixin, DeleteView):
    model = Type
    template_name = 'tools/type_templates/type_confirm_delete.html'
    success_url = reverse_lazy('tools:list_type')


class UpdateType(LoginRequiredMixin, views.SuccessMessageMixin, UpdateView):
    model = Type
    fields = "__all__"
    template_name_suffix = 'tools/type_templates/type_form.html'
    success_url = reverse_lazy('tools:list_type')

tools/templates/tools/type_templates/listView.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Tools - {{ user.first_name }}
{% endblock %}

{% block content %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">List Of Types</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="StandardTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <td>#</td>
                        <th>Type</th>
                        <th>Actions</th>

                    </tr>
                </thead>
                <tbody>
                {% for i in list_objects %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ i.name }}</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a href="{% url 'tools:update_type' i.pk %}" class="btn btn-warning btn-sm ">Update</a>
                                <a href="{% url 'tools:delete_type' i.pk %}" class="btn btn-danger btn-sm ">delete</a>
                            </div>
                        </td>

                    </tr>
                {% endfor  %}
                </tbody>
            </table>
        </div>
        <br>
        <a class="btn btn-success" href="{% url 'tools:create_type' %}">Create Type</a>
        <a class="btn btn-success" href="{% url 'tools:home' %}">Tools Section</a>
    </div>

</div>

{% endblock %}

tools/templates/tools/type_templates/type_confirm_delete.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Delete
{% endblock title %}

{% block content %}
<div class='container'>
    <h1>Type Delete</h1>
    <form method="post">
        {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    </form>
    </div>
{% endblock content %}

tools/templates/tools/type_templates/type_form.html
{% extends 'private_area/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Tools - {{ user.first_name }}
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Add" class="btn btn-success">
        <a class="btn btn-success" href="{% url 'tools:list_type' %}">All Items</a>
    </form>
</div>

{% endblock %}